### ISSUE TITLE
Publish daily/weekly stats from GA and disqus

### ISSUE THREAD

**Issue by DinisCruz** [project-cx/pbx-group-security#107]
And other stats we have 

The daily can be done on the GS-CST slack channel 

The weekly should be done as blog posts in this site

**Comment by fzipi** [comment]
@DinisCruz Daily stats can be pushed using [Arc](https://gs-cst.slack.com/apps/A0G0Q15F1-arc) or using http://datacard.io/.

**Comment by fzipi** [comment]
We have reached our limit for apps in Slack, so we need to change plan or delete something...

**Comment by Abhi-Raj** [comment]
@fzipi have cleaned few applications which we didn't use. We should be able to get new apps tested.

**Comment by fzipi** [comment]
Good, after that I added arc to send daily analytics to the slack channel.

**Comment by DinisCruz** [comment]
nice, only worry with these services is how secure our data/access-key is handled by them

**Comment by DinisCruz** [comment]
Since we have the stats sent daily, we can close this now
