### ISSUE TITLE
Need to improve default images on blog

### ISSUE THREAD

**Issue by DinisCruz** [project-cx/pbx-group-security#114]
maybe having a library of images that we can use?

https://pbx-group-security.com/blog/

**Comment by fzipi** [comment]
I've been using high quality CC photos from [unsplash](https://unsplash.com/).

**Comment by JemmaDSmith** [comment]
pixabay.com and pixels.com are good sources of CC images too.

Shall we ask Javier to come up with a bank of images around categories and labels?

**Comment by DinisCruz** [comment]
this has been done (by @javieralvarezgrafico )
