### ISSUE TITLE
Twitter and LinkedIn blog post thumbnails are not working

### ISSUE THREAD

**Issue by DinisCruz** [project-cx/pbx-group-security#115]
**Twitter**

![image](https://user-images.githubusercontent.com/656739/34084670-6d61aeac-e37c-11e7-8621-8997393884c9.png)

**LInkedIn**

![image](https://user-images.githubusercontent.com/656739/34084677-85e4a498-e37c-11e7-9402-f0212468582b.png)

**Comment by DinisCruz** [comment]
We also need to fix this one  (on the roles page)

![image](https://user-images.githubusercontent.com/656739/34086297-aa94f944-e392-11e7-97c4-35c61cae794a.png)

**Comment by fzipi** [comment]
For image in twitter, you need to add an `image:` to the front-matter. For the linkedin, let me see if it is another card format.

**Comment by fzipi** [comment]
Algo, if you add your twitter handle (as the author of the post) it will be presented in the card. Just add `twitter: <your handle>` (without `@`).

**Comment by fzipi** [comment]
Well, it seems that we only need and `images:` in each post. As there is no images, hugo uses the 'Params.logo' defined in the config.toml. But that image was relative. I changed it to absolute.

**Comment by fzipi** [comment]
@DinisCruz So, after adding `images:`, twitter is working. The problem with roles content type is that there are no images to show by default.

So, if we need to publish a nice roles page in linkedin, then we need cool images...

**Comment by fzipi** [comment]
Here is how I see now the post in linkedin:
![screenshot from 2017-12-18 23-08-10](https://user-images.githubusercontent.com/3012076/34137209-6d394cb0-e448-11e7-9829-8f0fb0c59f71.png)

**Comment by fzipi** [comment]
Solved. Now linking from social media is consistent in imaging, title, and summary.

![screenshot from 2017-12-18 23-43-24](https://user-images.githubusercontent.com/3012076/34138243-550223b0-e44d-11e7-86fc-2df644d20481.png)

**Comment by JemmaDSmith** [comment]
@fzipi do we need designs for the roles? We can brief design requirements in cx-design slack channel. Javier knows our look, feel and pallet

**Comment by fzipi** [comment]
@JemmaDSmith I would like that the roles should have nice designs, yes.

**Comment by DinisCruz** [comment]
Closing since this is now working ok
![image](https://user-images.githubusercontent.com/656739/34636251-38838c32-f295-11e7-860a-2a618d45b84f.png)
