### ISSUE TITLE
Improve printing page

### ISSUE THREAD

**Issue by DinisCruz** [project-cx/pbx-group-security#125]
For example it would be good to show a banner

![image](https://user-images.githubusercontent.com/656739/34116161-a40cfc20-e40f-11e7-88b9-b86667395d81.png)

**Comment by fzipi** [comment]
I've added in 3233f2a a partial for printing some banner. Right now is printing the logo, but not nicely. Please choose a nice image for printing first 🙂

**Comment by JemmaDSmith** [comment]
@fzipi do you have an image spec?

**Comment by fzipi** [comment]
I think for an A4 print a nice header will be around 540 x 120px.

**Comment by DinisCruz** [comment]
Btw, the challenges pages all print ok (did a bunch of CSS hacks to make it work)

**Comment by DinisCruz** [comment]
Closing this since I'm quite happy with the current page print (@fzipi can you open an separate issue 
 for https://github.com/project-cx/pbx-group-security/issues/125#issuecomment-353651210 )

![image](https://user-images.githubusercontent.com/656739/34636169-c7d42786-f293-11e7-9646-757362ac8c31.png)
