### ISSUE TITLE
Add subscribe button to website

### ISSUE THREAD

**Issue by zsofiasomlai** [project-cx/pbx-group-security#129]

**Comment by fzipi** [comment]
@zsofiasomlai It would be nice to know where to subscribe...

**Comment by zsofiasomlai** [comment]
Sorry... very new to this. We were just chatting with Dinis that once there's enough content on the blog, we should offer the option for visitors to subscribe and get a notification when new content is published, or if there will be a lot of content going up, maybe just get a notification about highlighted pieces.

**Comment by fzipi** [comment]
Don't worry. Just to know if there is something that should be made, or if was just a "reminder". Right now there is an RSS feed generated by default with the content, that gets updated when there is new content....

**Comment by DinisCruz** [comment]
We can do this now for blogs since that is where we can add news and other items (and it will be easier for the users to subscribe)

**Comment by fzipi** [comment]
I'm adding this button for subscribe to rss feed:
![screenshot from 2018-01-07 18-20-17](https://user-images.githubusercontent.com/3012076/34654220-90367992-f3d7-11e7-873e-ff5054ffb395.png)
Needs a little css tweaking, and it will be done.

**Comment by fzipi** [comment]
Now it looks like this:
![screenshot from 2018-01-07 18-54-25](https://user-images.githubusercontent.com/3012076/34654555-3b41150a-f3dc-11e7-8d04-5f11255df033.png)

@DinisCruz Is that fine for you?

**Comment by zsofiasomlai** [comment]
Instead of 'subscribe me' can you just say either 'Subscribe' or 'Subscribe here'?

Thanks!

**Comment by fzipi** [comment]
@zsofiasomlai It says 'Subscribe' now. And it's live!
