### ISSUE TITLE
Add footer note to website with reference that all content is released under CC-SA

### ISSUE THREAD

**Issue by DinisCruz** [project-cx/pbx-group-security#149]
CC Share Alike license

Idea is to make it obvious that the content is being released for the community (and that all content contributions must be done using the same licence)

On that note, can we add that reference to the Contributor agreement?

**Comment by fzipi** [comment]
Do you prefer in the footer: ![screenshot from 2018-01-05 09-21-01](https://user-images.githubusercontent.com/3012076/34609039-d3d62588-f1f9-11e7-881a-9609ed05658e.png)

Or before:
![screenshot from 2018-01-05 09-26-49](https://user-images.githubusercontent.com/3012076/34609233-a6e3e032-f1fa-11e7-9f9c-cb4328ae4ffb.png)

**Comment by DinisCruz** [comment]
Footer looks better :)

**Comment by fzipi** [comment]
Footer it is. I removed the image because it was to big for the footer, and the colors had too much contrast.

Commited in 6109eba.
