### ISSUE TITLE
Change hugo templates to baseof and defines

### ISSUE THREAD

**Issue by fzipi** [project-cx/pbx-group-security#151]
We are repeating for each content all the default template, and it is not needed.

The solution is to change to a main baseof.html. and just rewrite each part using defines.

I will post and example here, and create a branch afterwards.

**Comment by fzipi** [comment]
This is a classic `baseof.html` template:
```
<!DOCTYPE html>
<html lang="{{ with .Site.LanguageCode }}{{ . }}{{ else }}en{{ end }}">
  <head>
    <meta charset="utf-8">
  ....
  </head>
  <body>
    {{ block "nav" . }}{{ partial "site-nav.html" . }}{{ end }}
    {{ block "header" . }}{{ end }}
    <main role="main" class="container">
      {{ block "test" . }}{{ end }}
      {{ block "content" . }}{{ end }}
    </main>

    {{ block "footer" . }}{{ partial "site-footer.html" . }}{{ end }}
    {{ block "scripts" . }}{{- partial "site-scripts.html" . -}}{{ end }}
    {{ block "deferscripts" . }}{{ end }}
  </body>
</html>
```
Then in each `single.html`, you only do:
```
{{ define "content" }}
  <the content>
{{ end }}
```
So there is no need to repeat all again. Just the content part.

**Comment by DinisCruz** [comment]
very cool, it works really well , just tried it for the /candidates page

![image](https://user-images.githubusercontent.com/656739/34636574-6b344796-f29c-11e7-8996-9e12e3b2eb88.png)

![image](https://user-images.githubusercontent.com/656739/34636575-6fa49c68-f29c-11e7-8f25-ff3e79be6457.png)

will create 

![image](https://user-images.githubusercontent.com/656739/34636576-75b3749e-f29c-11e7-9e01-c1a53c60c737.png)

**Comment by DinisCruz** [comment]
this is done
