### ISSUE TITLE
Trust connections - take down article

### ISSUE THREAD

**Issue by zsofiasomlai** [project-cx/pbx-group-security#152]
Hi Dinis,

Just sent you a separate email about this, as I mentioned it on the team meeting, I think we have to take this piece down: https://pbx-group-security.com/blog/2017/12/15/using-trust-connections-for-referrals/ 

Thanks,

Zsofi

**Comment by DinisCruz** [comment]
done, this page is not there anymore

![image](https://user-images.githubusercontent.com/656739/34636154-69a12b3c-f293-11e7-9d81-bcf42e63f3bb.png)
