### ISSUE TITLE
insert html into md

### ISSUE THREAD

**Issue by JemmaDSmith** [project-cx/pbx-group-security#155]
pbx-group-security/content/page/rules-of-engagement.md

Google tells me it is possible to add inline html into md

https://stackoverflow.com/questions/14951321/how-to-display-html-content-in-github-readme-md

What am I doing wrong?

**Comment by fzipi** [comment]
@JemmaDSmith You are mixing templates and content :)

That code is for the templates, it has go templates code in it. What do you want to do?

**Comment by JemmaDSmith** [comment]
insert the contract roles into this page

**Comment by fzipi** [comment]
Good. Let me create a layout for that.
