### ISSUE TITLE
ux: Navbar wraps in portrait mode below 990px wide screen resolution

### ISSUE THREAD

**Issue by RandomFractals** [project-cx/pbx-group-security#232]
![pbx-group-security-top-nav](https://user-images.githubusercontent.com/656833/34887878-a49d863c-f78d-11e7-97dd-b8558ccafd8c.png)

it changes to the hamburger menu at 767px wide and below.

We should either do same for the 760px to 990px wide desktop screens or condense menu items for a resolution in that range to fit in one row without Contact menu item wrapping.

**Comment by RandomFractals** [comment]
need to look into custom media navbar CSS rules set in to fix this: 
https://github.com/project-cx/pbx-group-security/blob/master/src/styles/css/style.default.css

**Comment by DinisCruz** [comment]
I think on that one we should remove the items from that menu (like the 'For Recuiters'

**Comment by RandomFractals** [comment]
@DinisCruz I am not sure just removing 'For Recruiters' would help there.

Also, is that your final branding logo? 

I suspect what happened there placeholder Hugo theme logo was replaced but CSS stylesheets were not properly updated to accomodate for the wider logo size and top nav to collapse when standard 960 or 720px resolutions are reached.

Rather than do a hack like remove some links for smaller screens, I'd recommend changing top nav links to a hamburger menu as most users accustomed to bootstrap UI webapps would expect.

   @JemmaDSmith @Abhi-Raj what are your thoughts on this?

**Comment by RandomFractals** [comment]
this was resolved in PR #250, merged into master, and can now be closed
