### ISSUE TITLE
Add links to simpler version of the challenges table

### ISSUE THREAD

**Issue by RandomFractals** [project-cx/pbx-group-security#233]
https://pbx-group-security.com/challenges/table/

Currently that page only displays challenges mapped by Area without links to the actual challenge details

![pbx-group-security-challenges-table](https://user-images.githubusercontent.com/656833/34889716-ab0e09a4-f794-11e7-952b-b5177f09380f.png)

Also should probably link key column in challenges list view similar to how it is done on the simple table view page

**Comment by DinisCruz** [comment]
Actually the link was on the Key :)

Merged the PR so this should be Fixed

**Comment by RandomFractals** [comment]
Actually, in condensed view there was a link on the Key column and in list view there was a link on the Title column.

@JemmaDSmith and me decided in design thread in Slack we should probably have them on both columns in both places as they lead to different pages.
