### ISSUE TITLE
removed 'For Recruitment' link from top menu

### ISSUE THREAD

**Issue by DinisCruz** [project-cx/pbx-group-security#240]
here 
![image](https://user-images.githubusercontent.com/656739/34910326-47e70224-f8aa-11e7-9fc6-593d4c4c2354.png)

It should go somewhere on the [roles](https://pbx-group-security.com/roles/) page

CC: @RandomFractals

**Comment by RandomFractals** [comment]
That makes sense. Let's decide where.

For Recruiters page only has this disclaimer text and lists Contract Positions from Roles page:

"Photobox Group are not looking to work with recruitment agencies for any permanent roles listed on this site.

If you have any suitable candidates for the contract positions listed below please email us."

btw, is group a plural in UK English? I think it should be: "Photobox Grous IS NOT..."

So, why don't we add this disclaimer to the top or bottom of the Roles page, or if recruiters can email only for the 'Contract' positions slap that text below Contract Positions table header or its footer.

Need specific instructions where in Roles :)

**Comment by RandomFractals** [comment]
How about I'll create a for-recruiters PR with a fix for this and #232 

I'll place that 'for recruiters' disclaimer text at the bottom of the Roles page for now so we can see how it looks and finalize this.

**Comment by RandomFractals** [comment]
Looking good! I moved that 'for recruiters' disclosure to the roles page header content.

This does fix issue #232 as @DinisCruz suspected :)

I removed For Recruiters menu item from Hugo config as well.

This is what it looks like now. Sending PR.

![pbx-combine-roles-for-recruiters](https://user-images.githubusercontent.com/656833/34919323-74aa01da-f927-11e7-8151-a4ad30e41961.png)

**Comment by RandomFractals** [comment]
resolved and merged in PR #250 Please close this issue.
