### ISSUE TITLE
make the short table the main table in the 'challenges' page

### ISSUE THREAD

**Issue by DinisCruz** [project-cx/pbx-group-security#241]
this one 
![image](https://user-images.githubusercontent.com/656739/34910728-5b4fead4-f8b3-11e7-8fb0-3ecefb72a7bf.png)

is used instead of 

![image](https://user-images.githubusercontent.com/656739/34910729-65b06ef4-f8b3-11e7-9c6d-0a7578f71cc0.png)

Couple items to take into consideration:

 - keep the text and links on the current https://pbx-group-security.com/challenges/ page
 - The cards used in the table view needs to have a min view since they do't wrap up well on small or mobile views (see below)

![image](https://user-images.githubusercontent.com/656739/34910737-9694542c-f8b3-11e7-9964-0dd84b21e90c.png)

**Comment by RandomFractals** [comment]
easy. then only change this text in new Roles page:

"See this page for a simpler version of the table below."

to:

"See this page for  all the challenges with skills information." ???

Need final text verbage approval for that change to implement it.

**Comment by RandomFractals** [comment]
swapped pages pics:

![pbx-shortchallengeslist](https://user-images.githubusercontent.com/656833/34925636-2d69d04a-f970-11e7-8deb-15b63debecd9.png)

**NOTE:** last sentence change in that page content: "See this page for All Challenges with skills information". Let me know if that works, or requires a copy edit.

![pbx-newchallengestable](https://user-images.githubusercontent.com/656833/34925641-391e1bb2-f970-11e7-87f1-085e2246db82.png)

**Comment by RandomFractals** [comment]
I moved scaling on mobile part reported by Dinis to issue #144, where it belongs with the challenges list card height CSS fixes it requires. 

This issue can be closed when challenges pages swap PR is merged.
