### ISSUE TITLE
Create google form for Candidate feedback on the challenges

### ISSUE THREAD

**Issue by Abhi-Raj** [project-cx/pbx-group-security#248]
Create a simple Google Forms, to provide feedback for the challenges.

The idea is that we have a simple Google Form that people cannot see the answer. We add in the bottom of each challenge, on the challenge page, things like:

- does the challenge make sense?
- was it difficult? / was it easy? / was is hard?" and add this to your update email? etc.

**Comment by RandomFractals** [comment]
great I idea. I am linking a related issue #257 Abhi created.
