### ISSUE TITLE
Refactoring hugo layouts using blocks and baseof.html

### ISSUE THREAD

**Issue by regisphilibert** [project-cx/pbx-group-security#273]
I can see the layouts never use the block extension method from baseof.html.
Which results in a lot of redundancies.
For exemple many layout files start this way: (there are many more shared lines, but we'll stick to those 12 for the exemple).
```
<!DOCTYPE html>
<html lang="{{ .Site.LanguageCode }}">
  {{ partial "head.html" . }}
  <body>
    <div id="all">
        <header>
          {{ partial "nav.html" . }}
        </header>
        {{ partial "breadcrumbs.html" . }}
        <div id="content">
            <div class="container">
```

If we were to use the baseof.html properly (it is not used as of today)
Then those 12 lines of codes (and their corresponding closing statements) would be in the baseof.html of _default/ or the section's layout dir.  (any section can have its own baseof.html)

Our layout would then contains this wrapping of singular part of the page instead of those redundant lines:
```
{{ define "main" }}
 [ page dedicated html ]
{{ end }}
```

This would need some time to make sure the overhaul doesn't break anything but we would gain a lot of time in the long run when maintaining/creating layouts (avoid having to copy/paste a major layout change in every layout files). Plus we'd follow Hugo's preferred way.

Of course if there are any particular reasons as of why this method was used instead of the Hugo preferred one, please let me know.

Correction: I can see 3 layouts use the baseof.html
* candidate/single.html
* roles/role-upwork.html
* roles/role.html

That's how ideally all our layout files should look like ;)

**Comment by RandomFractals** [comment]
I agree. Let's bite on this next week?

**Comment by regisphilibert** [comment]
Yes ideally I'd like to do this as a one shot during a low "template mingling" day.
To avoid too much conflicts with other people's template coding. A lot of files will be impacted.

**Comment by RandomFractals** [comment]
Agreed. I'll work on tests and you can take a stab at this refactor next week.

**Comment by regisphilibert** [comment]
There seem to have been a holdout on this issue. Is it resolved? 
I can see that very few people are working on the layouts these days and it would be the perfect time to handle this task. 
@DinisCruz what do you think?

**Comment by fzipi** [comment]
@regisphilibert I would say that you just do this. I am sure Dinis already has a lot on his plate...

**Comment by regisphilibert** [comment]
@fzipi Yes thanks for digging that old thing! I assume not too many people are playing with the templates these days anyway. 
Will take care of this tomorrow.

**Comment by regisphilibert** [comment]
https://github.com/project-cx/pbx-group-security/pull/384
