### ISSUE TITLE
Invalid pygments error

### ISSUE THREAD

**Issue by DinisCruz** [project-cx/pbx-group-security#297]
Hi @regisphilibert can you try to find the root cause of this error message (and see if there are any side effects caused by it?)

![image](https://user-images.githubusercontent.com/656739/35476891-35af72b0-03b0-11e8-9111-0b171ae377f1.png)

**Comment by regisphilibert** [comment]
@DinisCruz you took me idled and I couldn't resist solving that puzzle before going out...

Here's the culprit: https://github.com/project-cx/pbx-group-security/blob/master/layouts/graph/graph-dot-2.html#L19

That second argument "en" is passed as LANG while "html" is passed as a pygment OPTION which doesn't exit.
See https://gohugo.io/functions/highlight/

replace by 
```
{{ highlight (partial "graph/dot-data.html" .) "html" ""  }}
``` 
and all will be good.

Will do it myself monday if you haven't already.

Cheers
