### ISSUE TITLE
(Tone review needed- fixed) same article Cat/Tags issue

### ISSUE THREAD

**Issue by m4sterbunny** [project-cx/pbx-group-security#322]
https://github.com/project-cx/pbx-group-security/blob/master/content/blog/drafts/TW/MarkDownYousay.md

**Comment by m4sterbunny** [comment]
article is live and corrections make online

**Comment by m4sterbunny** [comment]
Oops- the date is wrong and no category tags have yet been applied!
![image](https://user-images.githubusercontent.com/20266893/36059580-7f4c58aa-0e43-11e8-8a89-496b64ece111.png)

**Comment by m4sterbunny** [comment]
cleared cache- still not getting date fix:
![image](https://user-images.githubusercontent.com/20266893/36059676-5459f60a-0e45-11e8-8f4b-1e26e2badceb.png)

**Comment by m4sterbunny** [comment]
Regis- date fix came through, was nothing to do with my cache. Just the refresh time is much slower than I anticipated (I think it took more than 15mins).

Can you talk to the issue of categories and tags- is there somewhere that I can go see the data-set/array for both so that I can choose from existing rather than create multi-versions when I cat/tag an article?

**Comment by regisphilibert** [comment]
Hi @m4sterbunny let's discuss this here: https://github.com/project-cx/pbx-group-security/issues/381

**Comment by m4sterbunny** [comment]
@Ambg05 @gracerpmg you were both very disciplined with regards to creating categories and tags. Do you have a solution for storing and calling them in such a way that we do not create multiple variants of the same concept?

**Comment by Ambg05** [comment]
HI m4sterbunny, sorry for the delay in responding to you. Re: categories & tags, I will need to refresh my memory! Maybe we should have another meeting next week (i’m on a training course all this week) and work it out together?

**Comment by m4sterbunny** [comment]
Regis has come up with a work-around solution for us- that is summarising all the cat/tags in one place, so that writers can choose from the existing set before creating a new one. Probably a workable plan.
![image](https://user-images.githubusercontent.com/20266893/36355016-43dd79d6-14e5-11e8-9898-8f6f96e3af77.png)
