### ISSUE TITLE
image not rendering on site

### ISSUE THREAD

**Issue by m4sterbunny** [project-cx/pbx-group-security#325]
https://github.com/project-cx/pbx-group-security/edit/master/content/blog/dinis/why-challenges.md

reviews fine within GitHub 
but on site simply says "infographic"

please advise

**Comment by m4sterbunny** [comment]
This one also 
https://pbx-group-security.com/blog/1/01/01/markdownyousay/

I have checked link and it should have survived file relocation!

**Comment by regisphilibert** [comment]
Hi @m4sterbunny, you must not include the `static` bit in the url.
`![image of dandelions](/img/blog.jpg) image of dandelions` ✅ 
`![image of dandelions](/static/img/blog.jpg) image of dandelions` 🚫 
Do you want me to make the changes ? (if there are a lot, I can do a search and replace to make the change quick)

**Comment by m4sterbunny** [comment]
Thanks! No I will edit cause if I DIY it might drive the message home (most folks need to do something 7 times to learn it!)

**Comment by regisphilibert** [comment]
GitHub just looks for the file in the repo.
When building the website Hugo takes everything from the **static** folder and drops it at the root of the website.
So /static/images/whatever.jpg will live on http://mywebsite.com/images/whatever.jpg
I can see why you'd rather be able to see the images straight from github but I don't see a valid solution for this.
Static must be left out I'm sorry.
