### ISSUE TITLE
Image size fix required

### ISSUE THREAD

**Issue by m4sterbunny** [project-cx/pbx-group-security#332]
https://github.com/project-cx/pbx-group-security/edit/master/content/blog/dinis/why-challenges.md

Infographic image too large- someone please train TW to apply appropriate CSS

**Comment by m4sterbunny** [comment]
I attempted to apply an approach I found elsewhere- but it was a fail
the most recent PR should be reverted - someone please train TW to revert PRs!

**Comment by regisphilibert** [comment]
Using the figure shortcode was a good idea. But we would have to make sure everybody uses it consistently.
Now, contrary to the usual markdown way of adding images, the shortcode needs an absolute URL, meaning : including the domain.
So this way:
```
{{< figure src="https://pbx-group-security.com/img/blog/Pbx_Security_Infographic_Amendments_HD300ppp.jpg" title="" width="720px" >}}
```

Now back to our styling issue, I can add a css to make sure the images contained in blogpost are contained in it and don't... go overboard.

**Comment by regisphilibert** [comment]
I was wrong about absolute URL and edited the post above.

**Comment by regisphilibert** [comment]
@m4sterbunny All is good on production after the fix. That image is heavy though :)
Cheers.
You don't have to use the figure shortcode but I personally think it is better practice. This way if we decide later on to change the html structure of our figure elements, it will replace all existing mention with the upgraded html.
