### ISSUE TITLE
Provide way for editors to list Category and Tags to avoid duplicates

### ISSUE THREAD

**Issue by regisphilibert** [project-cx/pbx-group-security#381]
Following https://github.com/project-cx/pbx-group-security/issues/322 I create an issue to discuss it.

**Comment by regisphilibert** [comment]
Two possibilities.
## 1/ The Hidden way. 
This will not really be hidden, but we could create an HTML with a hard to guess name at the root of the website anywhere else that lists existing tags and taxonomy. 
Editors could just hit something like https://pbx-group-security.com/list-taxonomies.html (could also be a .json but I suppose html will be easier to read.
`+` This is hidden from most visitors
`-` For the few visitors who will find it, this will not be pretty.
## 2/ The public way. 
Wee simply build 2 taxonomy pages, one for Categories and one for Tags. Now it may already exists...

**Comment by m4sterbunny** [comment]
Dinis- your articles never did get categories or tags applied. Do you have a solution in mind?

**Comment by m4sterbunny** [comment]
@DinisCruz see above!

**Comment by regisphilibert** [comment]
I'll build a quick stat page so you guys can see what i am talking about here.

**Comment by regisphilibert** [comment]
Ok : https://pbx-group-security.com/stats.html

Using this discreet url we now have basic outline of site content data which can help with the issue at hand: tags/categories duplicate. 

Of course we could add anything to this page if needed. I'm sure you guys may need other forms of data on the site content. (list of authors etc...) 

Feel free to open issues to add stats to the page.

Cheers

**Comment by m4sterbunny** [comment]
I love it - works a treat.
