### ISSUE TITLE
Change CI workflow so that dev.pbx-gs.com shows the Dev branch

### ISSUE THREAD

**Issue by DinisCruz** [project-cx/pbx-group-security#60]
That way real time changes and commits can be seen strait away and only when merging into master will those changes be seen in the main https://pbx-group-security.com

**Comment by fzipi** [comment]
You can have two configs, e.g. `config.toml` for production as it is now, and create another one `config-dev.toml`. In that case, each webhook can trigger one config or another...

**Comment by fzipi** [comment]
@DinisCruz For solving #110 , the CI pipeline has to take into account different configs.

So, I think in the `buildspec.yml` we need to input config as a parameter/env var, 

```
...
 build:
    commands:
- cd pbx-group-security && hugo --config=$HUGO_CONFIG
```

So HUGO_CONFIG will point to each different config per build. Or if we are talking about branches, just use `config.toml` when branch is `master`, or use `config-dev.toml` as default for all other branches.

**Comment by DinisCruz** [comment]
we don't really need this at the moment (with current workflow) so marking it as `not-implemented`
